[toolchain]

[features]
seeds = false
skip-lint = false

[programs.devnet]
nft = "133GmbTcPtmYQ2hsyZQypweZgXBEb8njhj7WUPQjcovM"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/cenwadike/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
